/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/web/1': RouteRecordInfo<
      '/web/1',
      '/web/1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/web/2': RouteRecordInfo<
      '/web/2',
      '/web/2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/web/3': RouteRecordInfo<
      '/web/3',
      '/web/3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/web/4': RouteRecordInfo<
      '/web/4',
      '/web/4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/web/5': RouteRecordInfo<
      '/web/5',
      '/web/5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/web/6': RouteRecordInfo<
      '/web/6',
      '/web/6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/web/7': RouteRecordInfo<
      '/web/7',
      '/web/7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/web/1.vue': {
      routes:
        | '/web/1'
      views:
        | never
    }
    'src/pages/web/2.vue': {
      routes:
        | '/web/2'
      views:
        | never
    }
    'src/pages/web/3.vue': {
      routes:
        | '/web/3'
      views:
        | never
    }
    'src/pages/web/4.vue': {
      routes:
        | '/web/4'
      views:
        | never
    }
    'src/pages/web/5.vue': {
      routes:
        | '/web/5'
      views:
        | never
    }
    'src/pages/web/6.vue': {
      routes:
        | '/web/6'
      views:
        | never
    }
    'src/pages/web/7.vue': {
      routes:
        | '/web/7'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
